export const dummyCalendarMoodData: Record<string, { mood: string; count: number }[]> = {
    "January": [ 
        {mood: "Happy", count: 10},
        {mood: "Sad", count: 5},
        {mood: "Angry", count: 1},
        {mood: "Neutral", count: 10},
        {mood: "Very Happy", count: 5},
    ],
    "February": [ 
        {mood: "Happy", count: 10},
        {mood: "Sad", count: 5},
        {mood: "Angry", count: 1},
        {mood: "Neutral", count: 6},
        {mood: "Very Happy", count: 6},
    ],
    "March": [ 
        {mood: "Happy", count: 12},
        {mood: "Sad", count: 6},
        {mood: "Angry", count: 1},
        {mood: "Neutral", count: 8},
        {mood: "Very Happy", count: 4},
    ],
    "April": [ 
        {mood: "Happy", count: 10},
        {mood: "Sad", count: 4},
        {mood: "Angry", count: 2},
        {mood: "Neutral", count: 8},
        {mood: "Very Happy", count: 6},
    ],
    "May": [
        {mood: "Happy", count: 11},
        {mood: "Sad", count: 5},
        {mood: "Angry", count: 3},
        {mood: "Neutral", count: 7},
        {mood: "Very Happy", count: 5},
    ],
    "June": [
        {mood: "Happy", count: 9},
        {mood: "Sad", count: 5},
        {mood: "Angry", count: 2},
        {mood: "Neutral", count: 7},
        {mood: "Very Happy", count: 7},
    ],
    "July": [
        {mood: "Happy", count: 12},
        {mood: "Sad", count: 6},
        {mood: "Angry", count: 2},
        {mood: "Neutral", count: 8},
        {mood: "Very Happy", count: 3},
    ],
    "August": [
        {mood: "Happy", count: 11},
        {mood: "Sad", count: 6},
        {mood: "Angry", count: 3},
        {mood: "Neutral", count: 7},
        {mood: "Very Happy", count: 4},
    ],
    "September": [
        {mood: "Happy", count: 10},
        {mood: "Sad", count: 5},
        {mood: "Angry", count: 3},
        {mood: "Neutral", count: 6},
        {mood: "Very Happy", count: 6},
    ],
    "October": [
        {mood: "Happy", count: 11},
        {mood: "Sad", count: 6},
        {mood: "Angry", count: 3},
        {mood: "Neutral", count: 7},
        {mood: "Very Happy", count: 4},
    ],
    "November": [
        {mood: "Happy", count: 10},
        {mood: "Sad", count: 5},
        {mood: "Angry", count: 2},
        {mood: "Neutral", count: 7},
        {mood: "Very Happy", count: 6},
    ],
    "December": [
        {mood: "Happy", count: 10},
        {mood: "Sad", count: 6},
        {mood: "Angry", count: 2},
        {mood: "Neutral", count: 8},
        {mood: "Very Happy", count: 5},
    ]
};

